---
kind: Service
apiVersion: v1
metadata:
  name: kafka-rest-proxy
  namespace: kafka
  labels:
    app: kafka-rest-proxy
spec:
  selector:
    app: kafka-rest-proxy
  ports:
  - name: web
    port: 8082