---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoonavigator
  namespace: kafka
  labels:
    app: zoonavigator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoonavigator
  template:
    metadata:
      labels:
        app: zoonavigator
    spec:
      containers:
      - name: zoonavigator-client
        image: elkozmon/zoonavigator-web:0.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: WEB_HTTP_PORT
          value: "8001"
        - name: API_HOST
          value: localhost
        - name: API_PORT
          value: "9000"
        - name: AUTO_CONNECT_CONNECTION_STRING
          value: zookeeper:2181
      - name: zoonavigator-api
        image: elkozmon/zoonavigator-api:0.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: API_HTTP_PORT
          value: "9000"
