---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remora
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: remora
  replicas: 1
  template:
    metadata:
      labels:
        app: remora
    spec:
      containers:
      - name: remora
        image: registry.opensource.zalan.do/machina/remora
        ports:
        - containerPort: 9000
        env:
          - name: KAFKA_ENDPOINT
            value: bootstrap:9092
---
kind: Service
apiVersion: v1
metadata:
  name: remora
  namespace: kafka
spec:
  selector:
    app: remora
  ports:
  - port: 9000
