---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-schema-registry
  namespace: kafka
  labels:
    app: cp-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-schema-registry
  template:
    metadata:
      labels:
        app: cp-schema-registry
    spec:
      containers:
      - name: cp-schema-registry
        image: confluentinc/cp-schema-registry:4.1.0
        imagePullPolicy: Always
        lifecycle:
          postStart: 
            exec:
              command: ["/bin/sh", "-c", "unset SCHEMA_REGISTRY_PORT"]
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL 
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cp-schema-registry.kafka.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
---
apiVersion: v1
kind: Service
metadata:
  name: cp-schema-registry
  namespace: kafka
  labels:
    app: cp-schema-registry
spec:
  ports:
  - port: 8081
    name: cp-schema-registry
  selector:
    app: cp-schema-registry
---
